# Generated by Django 5.2.6 on 2025-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
            ],
        ),
    ]
