"""initial migration

Revision ID: 802522d4c423
Revises: 
Create Date: 2025-09-17 22:26:41.767178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802522d4c423'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
